/**
 * Bake Material Symbols SVG paths (downloaded to .iconsrc) into
 * src/data/icons.ts. Replaces the 672KB icon font with a few KB of
 * inline SVG. Icon names are discovered by scanning src for icon="..."
 * usages and data-file icon values — then any missing svgs are fetched
 * from jsdelivr automatically, so adding an icon in code "just works".
 */
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC = new URL('../.iconsrc/', import.meta.url);
const APP = fileURLToPath(new URL('../src/', import.meta.url));

/** icon names that alias to a different file name in the package */
const ALIAS = { expand_more: 'keyboard_arrow_down' };

// ---------------------------------------------------------------- names
function walk(dir, acc = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) walk(p, acc);
    else if (/\.(astro|ts|js)$/.test(entry.name)) acc.push(p);
  }
  return acc;
}

const used = new Set();
for (const f of walk(APP)) {
  const text = readFileSync(f, 'utf8');
  for (const m of text.matchAll(/icon="([a-z_0-9]+)"/g)) used.add(m[1]);
  for (const m of text.matchAll(/icon:\s*'([a-z_0-9]+)'/g)) used.add(m[1]);
  // icon names inside expressions, e.g. icon={cond ? 'a' : 'b'}
  for (const m of text.matchAll(/'([a-z][a-z_0-9]{2,})'/g)) {
    const n = m[1];
    // keep only names that look like material symbol ids
    if (/^(call|chat|star|search|info|list|check|close|hotel|person|timer|visibility|send|menu|home|map)$/.test(n) ||
        /^[a-z]+(_[a-z0-9]+)+$/.test(n)) {
      used.add(n);
    }
  }
}
used.delete(''); // defensive

// ------------------------------------------------------------- download
if (!existsSync(SRC)) mkdirSync(SRC);
const pkg = 'https://cdn.jsdelivr.net/npm/@material-symbols/svg-400@0.47.2/outlined';
const fetchOne = (file) => {
  const dest = new URL(`${file}.svg`, SRC);
  if (existsSync(dest)) return;
  try {
    execSync(`curl -sf --max-time 20 -o "${dest.pathname.replace(/^\//, '')}" "${pkg}/${file}.svg"`, { stdio: 'pipe' });
  } catch {
    console.warn(`⚠ no svg in package for "${file}"`);
  }
};

for (const name of used) {
  const file = ALIAS[name] ?? name;
  if (file === 'starFilled') continue;
  fetchOne(file);
}

// ---------------------------------------------------------------- bake
const parse = (svg) => {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? '0 -960 960 960';
  const d = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  return { viewBox, d };
};

const out = {};
for (const [name, file] of Object.entries(ALIAS)) {
  const p = new URL(`${file}.svg`, SRC);
  if (existsSync(p)) out[name] = parse(readFileSync(p, 'utf8'));
}

// Filled star for ratings (Material Icons "star", Apache 2.0) — the SVG-400
// package only ships outline styles; font's FILL axis has no static equivalent.
out.starFilled = {
  viewBox: '0 0 24 24',
  d: ['M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z'],
};

for (const f of readdirSync(SRC)) {
  if (!f.endsWith('.svg')) continue;
  const name = f.replace(/\.svg$/, '');
  if (out[name]) continue;
  out[name] = parse(readFileSync(new URL(f, SRC), 'utf8'));
}

const stillMissing = [...used].filter((n) => n !== 'starFilled' && !out[n] && !out[ALIAS[n] ?? n]);
if (stillMissing.length) console.warn('missing glyphs (add svgs to .iconsrc):', stillMissing.join(', '));

const ts = `/**
 * Material Symbols (SVG-400, outlined) — generated by scripts/bake-icons.mjs
 * from @material-symbols/svg-400 (Apache 2.0). Rendered by src/components/Icon.astro.
 */
export const icons: Record<string, { viewBox: string; d: string[] }> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(new URL('../src/data/icons.ts', import.meta.url), ts);
console.log(`✓ baked ${Object.keys(out).length} icons (${used.size} used by app)`);
