/**
 * Generates dist/sitemap.xml + dist/og.png after astro build.
 * (Hand-rolled instead of @astrojs/sitemap so we control Persian
 * entries, ordering, and the OG image without extra deps.)
 */
import { readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const SITE = 'https://best-of-iran.vercel.app';
const dist = fileURLToPath(new URL('../dist/', import.meta.url));

function pages(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) pages(p, acc);
    else if (name.endsWith('.html')) {
      let rel = '/' + p.slice(dist.length).replace(/\\/g, '/');
      rel = rel.replace(/index\.html$/, '').replace(/\.html$/, '');
      if (rel.length > 1) rel = rel.replace(/\/$/, '');
      acc.push(rel === '' ? '/' : rel);
    }
  }
  return acc;
}

// query-variants of category pages are canonical'd to the base page, so dedupe them
const urls = [...new Set(pages(dist))].filter((u) => !u.includes('/404'));

const now = new Date().toISOString().split('T')[0];
const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) =>
      `  <url><loc>${SITE}${u}</loc><lastmod>${now}</lastmod></url>`,
  )
  .join('\n')}
</urlset>
`;
writeFileSync(join(dist, 'sitemap.xml'), xml);
console.log(`✓ sitemap.xml — ${urls.length} urls`);

// og.png lives in public/ (generated by scripts/make-og.mjs) — not rebuilt
// here, so the static copy is always served without a build race.
