/**
 * Generates dist/sitemap.xml + dist/og.png after astro build.
 * (Hand-rolled instead of @astrojs/sitemap so we control Persian
 * entries, ordering, and the OG image without extra deps.)
 */
import { readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE = 'https://best-of-iran.pages.dev';
const dist = fileURLToPath(new URL('../dist/', import.meta.url));

function pages(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) pages(p, acc);
    else if (name.endsWith('.html')) {
      let rel = '/' + p.slice(dist.length).replace(/\\/g, '/');
      rel = rel.replace(/index\.html$/, '').replace(/\.html$/, '');
      if (rel.length > 1) rel = rel.replace(/\/$/, '');
      acc.push(rel === '' ? '/' : rel);
    }
  }
  return acc;
}

// query-variants of category pages are canonical'd to the base page, so dedupe them
const urls = [...new Set(pages(dist))].filter((u) => !u.includes('/404'));

const now = new Date().toISOString().split('T')[0];
const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) =>
      `  <url><loc>${SITE}${u}</loc><lastmod>${now}</lastmod></url>`,
  )
  .join('\n')}
</urlset>
`;
writeFileSync(join(dist, 'sitemap.xml'), xml);
console.log(`✓ sitemap.xml — ${urls.length} urls`);

// ------------------------------------------------------------------ rss.xml
const { articlesBySlug } = await import('../src/data/articles.ts');

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const items = Object.values(articlesBySlug)
  .map(
    (a) => `  <item>
    <title>${esc(a.title)}</title>
    <link>${SITE}/articles/${a.slug}</link>
    <guid isPermaLink="true">${SITE}/articles/${a.slug}</guid>
    <description>${esc(a.description)}</description>
    <dc:language>fa</dc:language>
    <pubDate>${new Date(a.isoDate).toUTCString()}</pubDate>
  </item>`,
  )
  .join('\n');

const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
<channel>
  <title>Best-of Iran — جدیدترین بررسی‌ها</title>
  <link>${SITE}</link>
  <description>مرجع تخصصی معرفی بهترین کسب‌وکارهای ایران با بررسی‌های دقیق و واقعی.</description>
  <language>fa</language>
${items}
</channel>
</rss>`;
writeFileSync(join(dist, 'rss.xml'), rss);
console.log(`✓ rss.xml — ${Object.keys(articlesBySlug).length} items`);

// ------------------------------------------------------------------ llms.txt
const llms = `# Best-of Iran

> ${esc('مرجع تخصصی معرفی بهترین کسب‌وکارهای ایران با بررسی‌های میدانی، رتبه‌بندی شفاف و تحلیل نظرات واقعی کاربران.')}
> رتبه‌ها خریدنی نیستند؛ روش ارزیابی عمومی است.

## Sections
- [خانه](${SITE}/): نمای کلی، پربازدیدهای هفته
- [مقالات و بررسی‌ها](${SITE}/articles): راهنماهای تخصصی رتبه‌بندی
- [پروفایل کسب‌وکارها](${SITE}/business/): اطلاعات تماس، امتیاز، نقشه
- [شهرها](${SITE}/cities): تهران، اصفهان، شیراز، مشهد، تبریز، کرج، اهواز
- [دسته‌بندی‌ها](${SITE}/categories): رستوران، کافه، کارواش، آرایشگاه، باشگاه، دندان‌پزشکی، هتل، پزشکی، وکلا
- [متدولوژی](${SITE}/methodology): روش ارزیابی (بازدید ناشناس، ۵۰+ شاخص، تحلیل نظرات)

## Recent articles
${Object.values(articlesBySlug)
  .map((a) => `- [${a.title}](${SITE}/articles/${a.slug}): ${a.description}`)
  .join('\n')}
`;
writeFileSync(join(dist, 'llms.txt'), llms);
console.log(`✓ llms.txt`);

// og.png lives in public/ (generated by scripts/make-og.mjs) — not rebuilt
// here, so the static copy is always served without a build race.
